apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.demoapp.name }}-cluster-service
                port:
                  number: {{ .Values.demoapp.servicePort }}
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fooapp.name }}-service
                port:
                  number: {{ .Values.fooapp.port }}
