apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.demoapp.name }}-cluster-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.demoapp.name }}
  ports:
    - name: http
      port: {{ .Values.demoapp.servicePort }}
      targetPort: {{ .Values.demoapp.containerPort }}
