apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fooApp.name }} # ใช้ชื่อจาก values.yaml
  labels:
    app: {{ .Values.fooApp.name }}
spec:
  replicas: 1 # กำหนด replicas สำหรับ foo-app
  selector:
    matchLabels:
      app: {{ .Values.fooApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fooApp.name }}
    spec:
      containers:
        - name: {{ .Values.fooApp.name }}
          image: "{{ .Values.fooApp.image.repository }}:{{ .Values.fooApp.image.tag }}"
          ports:
            - containerPort: {{ .Values.fooApp.containerPort }}
