apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fooService.name }} # ใช้ชื่อ Service จาก values.yaml
  labels:
    app: {{ .Values.fooApp.name }} # อ้างอิง label ของ fooApp
spec:
  selector:
    app: {{ .Values.fooApp.name }} # เลือก Pods ที่มี label ของ fooApp
  ports:
    - port: {{ .Values.fooService.port }} # ใช้ Port จาก values.yaml
      targetPort: {{ .Values.fooService.targetPort }} # ใช้ Target Port จาก values.yaml