apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} # ใช้ชื่อ Service จาก values.yaml
  labels:
    app: {{ .Values.mainApp.name }} # อ้างอิง label ของ mainApp
spec:
  type: {{ .Values.service.type }} # ใช้ Service Type จาก values.yaml
  selector:
    app: {{ .Values.mainApp.name }} # เลือก Pods ที่มี label ของ mainApp
  ports:
    - port: {{ .Values.service.port }} # ใช้ Port จาก values.yaml
      targetPort: {{ .Values.service.targetPort }} # ใช้ Target Port จาก values.yaml